#!/usr/bin/env bash

set -euo pipefail
THISDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

IMAGE_NAME="jfg.name"
CONTAINER_NAME="jfg.name-container"

function help(){
cat << EOF
joefg.pages.dev

help:                    Display help text
clean:                   Remove artefacts
lint:                    Lint project
build:                   Compile site
container <cmd|halt|rm>: Run command in container
serve:                   Serve on localhost:3000
EOF
}

function run_clean(){
    rm -rf _site/
}

function run_lint(){
    shellcheck "$THISDIR/run"
    (deno check && deno lint)
}

function run_build(){
    deno task build
}

function remove_container(){
    container_name="$1"
    docker ps -aq --filter "name=^?$container_name$" | xargs -r docker rm -f
}

function run_container(){
    cd "$THISDIR"
    cmd=${1-help}
    case "$cmd" in
        halt)
            docker kill "$CONTAINER_NAME"
            ;;
        rm)
            remove_container "$CONTAINER_NAME"
            ;;
        *)
            docker build . -t "$IMAGE_NAME"
            remove_container "$CONTAINER_NAME"
            docker run \
                -p 127.0.0.1:3000:3000 \
                --name "$CONTAINER_NAME" \
                "$IMAGE_NAME" "$cmd" 
            ;;
        esac
}

function run_serve(){
    deno task serve
}

function main(){
    cmd=${1-default}
    shift || true
    case "$cmd" in
        help|default)
            help "$@"
            ;;
        clean)
            run_clean
            ;;
        lint)
            run_lint
            ;;
        build)
            run_build
            ;;
        container)
            run_container "$@"
            ;;
        serve)
            run_serve
            ;;
        *)
            echo "no-op $cmd"
            ;;
    esac
}

main "$@"
