title: jfg.name
description: Software yapbox.

author:
  name: Joe
  email: me@jfg.name

github: https://github.com/joefg

header:
  title: jfg.name
  blurb: Consider the following.
  #mugshot: https://avatars.githubusercontent.com/u/13489445
  #links:
    #🖥️ GitHub: https://github.com/joefg
    
footer:
  text: Built with Deno and Lume in England 🏴󠁧󠁢󠁥󠁮󠁧󠁿
  repo: https://github.com/joefg/lume-simple-blog
  links:
    Colophon: /colophon
    Now: /now
