title: jfg.name

description: jfg.name, a blog

blurb: |
  Computer programmer.

footer: Made with deno and lume in England 🏴󠁧󠁢󠁥󠁮󠁧󠁿.

mugshot: https://avatars.githubusercontent.com/u/13489445

author:
  name: jfg
  email: jfg@jfg.name

github: https://github.com/joefg

repo: https://github.com/joefg/lume-simple-blog

#links:
#  📯 Telegram Channel: https://t.me/s/joefg_channel
