title: jfg.name
blurb: Computer Programmer
photo: https://avatars.githubusercontent.com/u/13489445

footer: >
  Made with lumetree in England 🏴󠁧󠁢󠁥󠁮󠁧󠁿 // ❤️

links:
  - title: 🖥️ GitHub
    url: https://github.com/joefg
  - title: 📧 E-Mail
    url: mailto://mr.jfg@proton.me
 
