title: jfg.name
description: Website 

author:
  name: Joe
  email: me@jfg.name

github: https://github.com/joefg

header:
  title: Joe Fuller-Gray • joefg
  #blurb: Joe Fuller-Gray
  #links:
    #🖥️ GitHub: https://github.com/joefg
    
footer:
  text: Built with Deno and Lume in England 🏴󠁧󠁢󠁥󠁮󠁧󠁿
  repo: https://github.com/joefg/lume-simple-blog
  links:
    Colophon: /colophon
    Now: /now
