title: jfg.name
blurb: Software Developer
photo: https://avatars.githubusercontent.com/u/13489445

footer: >
  Made with lumetree in England 🏴󠁧󠁢󠁥󠁮󠁧󠁿 // ❤️

text: >
  It's not the thing, it's the thing that gets us to the thing.

links:
  - title: 🖥️ GitHub
    url: https://github.com/joefg
  - title: 📧 E-Mail
    url: mailto://mr.jfg@proton.me
 
