title: joefg.github.io

description: jfg.name, a blog

#blurb: Computer programmer.

footer: Made with deno and lume in England 🏴󠁧󠁢󠁥󠁮󠁧󠁿.
#repo: https://github.com/joefg/lume-simple-blog

#mugshot: https://avatars.githubusercontent.com/u/13489445

author:
  name: jfg
  email: jfg@jfg.name

links:
  🖥️ GitHub: https://github.com/joefg
