name: Publish on GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.1.4

      - name: Build site
        run: ./run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site/'

  deploy:
      needs: build

      permissions:
        pages: write
        id-token: write

      runs-on: ubuntu-latest

      environment:
        name: cloudflare-pages
        url: ${{ steps.deployment.output.page_url }}

      steps:
        - name: Deploy to Cloudflare Pages
          id: deployment
          uses: cloudflare/wrangler-action@v3
          with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            workingDirectory: "_site"
